BEGIN TRANSACTION;

/* DROP FOREIGN KEYS */
ALTER TABLE [dbo].[additional_services] DROP CONSTRAINT [FK_additional_services_units];
ALTER TABLE [dbo].[additional_services_detail] DROP CONSTRAINT [FK_additional_services_detail_additional_services];
ALTER TABLE [dbo].[additional_services_detail] DROP CONSTRAINT [FK_additional_services_detail_languages];
ALTER TABLE [dbo].[additional_services_detail] DROP CONSTRAINT [FK_additional_services_detail_value_added_taxes];
ALTER TABLE [dbo].[campaigns] DROP CONSTRAINT [FK_campaigns_languages];
ALTER TABLE [dbo].[categories_detail] DROP CONSTRAINT [FK_categories_detail_categories];
ALTER TABLE [dbo].[categories_detail] DROP CONSTRAINT [FK_categories_detail_languages];
ALTER TABLE [dbo].[countries_detail] DROP CONSTRAINT [FK_countries_detail_countries];
ALTER TABLE [dbo].[countries_detail] DROP CONSTRAINT [FK_countries_detail_languages];
ALTER TABLE [dbo].[custom_themes_templates] DROP CONSTRAINT [FK_custom_themes_templates_custom_themes];
ALTER TABLE [dbo].[customers] DROP CONSTRAINT [FK_customers_languages];
ALTER TABLE [dbo].[customers] DROP CONSTRAINT [FK_customers_countries];
ALTER TABLE [dbo].[customers] DROP CONSTRAINT [FK_customers_invoice_countries];
ALTER TABLE [dbo].[customers_files] DROP CONSTRAINT [FK_customers_files_customers];
ALTER TABLE [dbo].[customers_files] DROP CONSTRAINT [FK_customers_files_products];
ALTER TABLE [dbo].[customers_files] DROP CONSTRAINT [FK_customers_files_languages];
ALTER TABLE [dbo].[discount_codes] DROP CONSTRAINT [FK_discount_codes_languages];
ALTER TABLE [dbo].[discount_codes] DROP CONSTRAINT [FK_discount_codes_currencies];
ALTER TABLE [dbo].[gift_cards] DROP CONSTRAINT [FK_gift_cards_languages];
ALTER TABLE [dbo].[gift_cards] DROP CONSTRAINT [FK_gift_cards_currencies];
ALTER TABLE [dbo].[languages_detail] DROP CONSTRAINT [FK_languages_detail_languages];
ALTER TABLE [dbo].[languages_detail] DROP CONSTRAINT [FK_languages_detail_translation_languages];
ALTER TABLE [dbo].[option_types_detail] DROP CONSTRAINT [FK_option_types_detail_languages];
ALTER TABLE [dbo].[option_types_detail] DROP CONSTRAINT [FK_option_types_detail_option_types];
ALTER TABLE [dbo].[options] DROP CONSTRAINT [FK_options_option_types];
ALTER TABLE [dbo].[options_detail] DROP CONSTRAINT [FK_options_detail_languages];
ALTER TABLE [dbo].[options_detail] DROP CONSTRAINT [FK_options_detail_options];
ALTER TABLE [dbo].[order_rows] DROP CONSTRAINT [FK_order_rows_orders];
ALTER TABLE [dbo].[order_rows] DROP CONSTRAINT [FK_order_rows_units];
ALTER TABLE [dbo].[orders] DROP CONSTRAINT [FK_orders_customers];
ALTER TABLE [dbo].[orders] DROP CONSTRAINT [FK_orders_delivery_countries];
ALTER TABLE [dbo].[orders] DROP CONSTRAINT [FK_orders_invoice_countries];
ALTER TABLE [dbo].[orders] DROP CONSTRAINT [FK_orders_payment_options];
ALTER TABLE [dbo].[orders] DROP CONSTRAINT [FK_orders_companies];
ALTER TABLE [dbo].[orders_gift_cards] DROP CONSTRAINT [FK_orders_gift_cards_orders];
ALTER TABLE [dbo].[newsletters] DROP CONSTRAINT [FK_newsletters_languages];
ALTER TABLE [dbo].[payment_options] DROP CONSTRAINT [FK_payment_options_units];
ALTER TABLE [dbo].[payment_options_detail] DROP CONSTRAINT [FK_payment_options_detail_languages];
ALTER TABLE [dbo].[payment_options_detail] DROP CONSTRAINT [FK_payment_options_detail_payment_options];
ALTER TABLE [dbo].[payment_options_detail] DROP CONSTRAINT [FK_payment_options_detail_value_added_taxes];
ALTER TABLE [dbo].[product_accessories] DROP CONSTRAINT [FK_product_accessories_accessory_product];
ALTER TABLE [dbo].[product_accessories] DROP CONSTRAINT [FK_product_accessories_products];
ALTER TABLE [dbo].[product_bundles] DROP CONSTRAINT [FK_product_bundles_product];
ALTER TABLE [dbo].[product_bundles] DROP CONSTRAINT [FK_product_bundles_bundle_product];
ALTER TABLE [dbo].[product_option_types] DROP CONSTRAINT [FK_product_option_types_option_types];
ALTER TABLE [dbo].[product_option_types] DROP CONSTRAINT [FK_product_option_types_products];
ALTER TABLE [dbo].[product_options] DROP CONSTRAINT [FK_product_options_options];
ALTER TABLE [dbo].[product_options] DROP CONSTRAINT [FK_product_options_product_option_types];
ALTER TABLE [dbo].[product_reviews] DROP CONSTRAINT [FK_product_reviews_customers];
ALTER TABLE [dbo].[product_reviews] DROP CONSTRAINT [FK_product_reviews_languages];
ALTER TABLE [dbo].[product_reviews] DROP CONSTRAINT [FK_product_reviews_products];
ALTER TABLE [dbo].[products] DROP CONSTRAINT [FK_products_categories];
ALTER TABLE [dbo].[products] DROP CONSTRAINT [FK_products_units];
ALTER TABLE [dbo].[products_detail] DROP CONSTRAINT [FK_products_detail_languages];
ALTER TABLE [dbo].[products_detail] DROP CONSTRAINT [FK_products_detail_products];
ALTER TABLE [dbo].[products_detail] DROP CONSTRAINT [FK_products_detail_value_added_taxes];
ALTER TABLE [dbo].[static_pages_detail] DROP CONSTRAINT [FK_static_pages_detail_languages];
ALTER TABLE [dbo].[static_pages_detail] DROP CONSTRAINT [FK_static_pages_detail_pages];
ALTER TABLE [dbo].[static_texts] DROP CONSTRAINT [FK_static_texts_languages];
ALTER TABLE [dbo].[units_detail] DROP CONSTRAINT [FK_units_detail_languages];
ALTER TABLE [dbo].[units_detail] DROP CONSTRAINT [FK_units_detail_units];
ALTER TABLE [dbo].[web_domains] DROP CONSTRAINT [FK_web_domains_back_end_languages];
ALTER TABLE [dbo].[web_domains] DROP CONSTRAINT [FK_web_domains_currencies];
ALTER TABLE [dbo].[web_domains] DROP CONSTRAINT [FK_web_domains_front_end_languages];
ALTER TABLE [dbo].[web_domains] DROP CONSTRAINT [FK_web_domains_countries];
ALTER TABLE [dbo].[web_domains] DROP CONSTRAINT [FK_web_domains_companies];

/* DROP PRIMARY KEYS */
ALTER TABLE [dbo].[additional_services] DROP CONSTRAINT [PK_additional_services];
ALTER TABLE [dbo].[additional_services_detail] DROP CONSTRAINT [PK_additional_services_detail];
ALTER TABLE [dbo].[administrators] DROP CONSTRAINT [PK_administrators];
ALTER TABLE [dbo].[campaigns] DROP CONSTRAINT [PK_campaigns];
ALTER TABLE [dbo].[categories] DROP CONSTRAINT [PK_categories];
ALTER TABLE [dbo].[categories_detail] DROP CONSTRAINT [PK_categories_detail];
ALTER TABLE [dbo].[companies] DROP CONSTRAINT [PK_companies];
ALTER TABLE [dbo].[countries] DROP CONSTRAINT [PK_countries];
ALTER TABLE [dbo].[countries_detail] DROP CONSTRAINT [PK_countries_detail];
ALTER TABLE [dbo].[currencies] DROP CONSTRAINT [PK_currencies];
ALTER TABLE [dbo].[custom_themes] DROP CONSTRAINT [PK_custom_themes];
ALTER TABLE [dbo].[custom_themes_templates] DROP CONSTRAINT [PK_custom_themes_templates];
ALTER TABLE [dbo].[customers_files] DROP CONSTRAINT [PK_customers_downloadable_files];
ALTER TABLE [dbo].[customers] DROP CONSTRAINT [PK_customers];
ALTER TABLE [dbo].[discount_codes] DROP CONSTRAINT [PK_discount_codes];
ALTER TABLE [dbo].[gift_cards] DROP CONSTRAINT [PK_gift_cards];
ALTER TABLE [dbo].[inspiration_image_maps] DROP CONSTRAINT [PK_inspiration_image_maps];
ALTER TABLE [dbo].[languages] DROP CONSTRAINT [PK_languages];
ALTER TABLE [dbo].[languages_detail] DROP CONSTRAINT [PK_languages_detail];
ALTER TABLE [dbo].[option_types] DROP CONSTRAINT [PK_option_types];
ALTER TABLE [dbo].[option_types_detail] DROP CONSTRAINT [PK_option_types_detail];
ALTER TABLE [dbo].[options] DROP CONSTRAINT [PK_options];
ALTER TABLE [dbo].[options_detail] DROP CONSTRAINT [PK_options_detail];
ALTER TABLE [dbo].[order_rows] DROP CONSTRAINT [PK_order_rows];
ALTER TABLE [dbo].[orders] DROP CONSTRAINT [PK_orders];
ALTER TABLE [dbo].[orders_gift_cards] DROP CONSTRAINT [PK_orders_gift_cards];
ALTER TABLE [dbo].[newsletters] DROP CONSTRAINT [PK_newsletters];
ALTER TABLE [dbo].[payment_options] DROP CONSTRAINT [PK_payment_options];
ALTER TABLE [dbo].[payment_options_detail] DROP CONSTRAINT [PK_payment_options_detail];
ALTER TABLE [dbo].[product_accessories] DROP CONSTRAINT [PK_product_accessories];
ALTER TABLE [dbo].[product_bundles] DROP CONSTRAINT [PK_product_bundles];
ALTER TABLE [dbo].[product_option_types] DROP CONSTRAINT [PK_product_option_types];
ALTER TABLE [dbo].[product_options] DROP CONSTRAINT [PK_product_options];
ALTER TABLE [dbo].[product_reviews] DROP CONSTRAINT [PK_product_reviews];
ALTER TABLE [dbo].[products] DROP CONSTRAINT [PK_products];
ALTER TABLE [dbo].[products_detail] DROP CONSTRAINT [PK_products_detail];
ALTER TABLE [dbo].[static_pages] DROP CONSTRAINT [PK_static_pages];
ALTER TABLE [dbo].[static_pages_detail] DROP CONSTRAINT [PK_static_pages_detail];
ALTER TABLE [dbo].[static_texts] DROP CONSTRAINT [PK_static_texts];
ALTER TABLE [dbo].[units] DROP CONSTRAINT [PK_units];
ALTER TABLE [dbo].[units_detail] DROP CONSTRAINT [PK_units_detail];
ALTER TABLE [dbo].[value_added_taxes] DROP CONSTRAINT [PK_value_added_taxes];
ALTER TABLE [dbo].[web_domains] DROP CONSTRAINT [PK_web_domains];
ALTER TABLE [dbo].[webshop_sessions] DROP CONSTRAINT [PK_webshop_sessions];
ALTER TABLE [dbo].[webshop_settings] DROP CONSTRAINT [PK_webshop_settings];

/* DROP CLUSTERED INDEXES */
DROP INDEX [CDX_additional_services] ON [dbo].[additional_services];
DROP INDEX [CDX_additional_services_detail] ON [dbo].[additional_services_detail];
DROP INDEX [CDX_administrators] ON [dbo].[administrators];
DROP INDEX [CDX_campaigns] ON [dbo].[campaigns];
DROP INDEX [CDX_categories] ON [dbo].[categories];
DROP INDEX [CDX_categories_detail] ON [dbo].[categories_detail];
DROP INDEX [CDX_companies] ON [dbo].[companies];
DROP INDEX [CDX_countries] ON [dbo].[countries];
DROP INDEX [CDX_countries_detail] ON [dbo].[countries_detail];
DROP INDEX [CDX_currencies] ON [dbo].[currencies];
DROP INDEX [CDX_custom_themes] ON [dbo].[custom_themes];
DROP INDEX [CDX_custom_themes_templates] ON [dbo].[custom_themes_templates];
DROP INDEX [CDX_customers_files] ON [dbo].[customers_files];
DROP INDEX [CDX_customers] ON [dbo].[customers];
DROP INDEX [CDX_discount_codes] ON [dbo].[discount_codes];
DROP INDEX [CDX_gift_cards] ON [dbo].[gift_cards];
DROP INDEX [CDX_inspiration_image_maps] ON [dbo].[inspiration_image_maps];
DROP INDEX [CDX_languages] ON [dbo].[languages];
DROP INDEX [CDX_languages_detail] ON [dbo].[languages_detail];
DROP INDEX [CDX_option_types] ON [dbo].[option_types];
DROP INDEX [CDX_option_types_detail] ON [dbo].[option_types_detail];
DROP INDEX [CDX_options] ON [dbo].[options];
DROP INDEX [CDX_options_detail] ON [dbo].[options_detail];
DROP INDEX [CDX_order_rows] ON [dbo].[order_rows];
DROP INDEX [CDX_orders] ON [dbo].[orders];
DROP INDEX [CDX_orders_gift_cards] ON [dbo].[orders_gift_cards];
DROP INDEX [CDX_newsletters] ON [dbo].[newsletters];
DROP INDEX [CDX_payment_options] ON [dbo].[payment_options];
DROP INDEX [CDX_payment_options_detail] ON [dbo].[payment_options_detail];
DROP INDEX [CDX_product_accessories] ON [dbo].[product_accessories];
DROP INDEX [CDX_product_bundles] ON [dbo].[product_bundles];
DROP INDEX [CDX_product_option_types] ON [dbo].[product_option_types];
DROP INDEX [CDX_product_options] ON [dbo].[product_options];
DROP INDEX [CDX_product_reviews] ON [dbo].[product_reviews];
DROP INDEX [CDX_products] ON [dbo].[products];
DROP INDEX [CDX_products_detail] ON [dbo].[products_detail];
DROP INDEX [CDX_static_pages] ON [dbo].[static_pages];
DROP INDEX [CDX_static_pages_detail] ON [dbo].[static_pages_detail];
DROP INDEX [CDX_static_texts] ON [dbo].[static_texts];
DROP INDEX [CDX_units] ON [dbo].[units];
DROP INDEX [CDX_units_detail] ON [dbo].[units_detail];
DROP INDEX [CDX_value_added_taxes] ON [dbo].[value_added_taxes];
DROP INDEX [CDX_web_domains] ON [dbo].[web_domains];
DROP INDEX [CDX_webshop_sessions] ON [dbo].[webshop_sessions];
DROP INDEX [CDX_webshop_settings] ON [dbo].[webshop_settings];

/* CREATE PRIMARY KEYS */
ALTER TABLE [dbo].[additional_services] ADD CONSTRAINT [PK_additional_services] PRIMARY KEY CLUSTERED ([id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[additional_services_detail] ADD CONSTRAINT [PK_additional_services_detail] PRIMARY KEY CLUSTERED ([additional_service_id] ASC, [language_id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[administrators] ADD CONSTRAINT [PK_administrators] PRIMARY KEY CLUSTERED ([id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[campaigns] ADD CONSTRAINT [PK_campaigns] PRIMARY KEY CLUSTERED ([id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[categories] ADD CONSTRAINT [PK_categories] PRIMARY KEY CLUSTERED ([id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[categories_detail] ADD CONSTRAINT [PK_categories_detail] PRIMARY KEY CLUSTERED ([category_id] ASC, [language_id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[companies] ADD CONSTRAINT [PK_companies] PRIMARY KEY CLUSTERED ([id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[countries] ADD CONSTRAINT [PK_countries] PRIMARY KEY CLUSTERED ([id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[countries_detail] ADD CONSTRAINT [PK_countries_detail] PRIMARY KEY CLUSTERED ([country_id] ASC, [language_id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[currencies] ADD CONSTRAINT [PK_currencies] PRIMARY KEY CLUSTERED ([currency_code] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[custom_themes] ADD CONSTRAINT [PK_custom_themes] PRIMARY KEY CLUSTERED ([id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[custom_themes_templates] ADD CONSTRAINT [PK_custom_themes_templates] PRIMARY KEY CLUSTERED ([custom_theme_id] ASC, [user_file_name] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[customers_files] ADD CONSTRAINT [PK_customers_downloadable_files] PRIMARY KEY CLUSTERED ([customer_id] ASC, [product_id] ASC, [language_id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[customers] ADD CONSTRAINT [PK_customers] PRIMARY KEY CLUSTERED ([id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[discount_codes] ADD CONSTRAINT [PK_discount_codes] PRIMARY KEY CLUSTERED ([id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[gift_cards] ADD CONSTRAINT [PK_gift_cards] PRIMARY KEY CLUSTERED ([id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[inspiration_image_maps] ADD CONSTRAINT [PK_inspiration_image_maps] PRIMARY KEY CLUSTERED ([id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[languages] ADD CONSTRAINT [PK_languages] PRIMARY KEY CLUSTERED ([id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[languages_detail] ADD CONSTRAINT [PK_languages_detail] PRIMARY KEY CLUSTERED ([language_id] ASC, [translation_language_id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[option_types] ADD CONSTRAINT [PK_option_types] PRIMARY KEY CLUSTERED ([id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[option_types_detail] ADD CONSTRAINT [PK_option_types_detail] PRIMARY KEY CLUSTERED ([option_type_id] ASC, [language_id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[options] ADD CONSTRAINT [PK_options] PRIMARY KEY CLUSTERED ([id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[options_detail] ADD CONSTRAINT [PK_options_detail] PRIMARY KEY CLUSTERED ([option_id] ASC, [language_id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[order_rows] ADD CONSTRAINT [PK_order_rows] PRIMARY KEY CLUSTERED ([order_id] ASC, [product_code] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[orders] ADD CONSTRAINT [PK_orders] PRIMARY KEY CLUSTERED ([id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[orders_gift_cards] ADD CONSTRAINT [PK_orders_gift_cards] PRIMARY KEY CLUSTERED ([order_id] ASC, [gift_card_id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[newsletters] ADD CONSTRAINT [PK_newsletters] PRIMARY KEY CLUSTERED ([id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[payment_options] ADD CONSTRAINT [PK_payment_options] PRIMARY KEY CLUSTERED ([id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[payment_options_detail] ADD CONSTRAINT [PK_payment_options_detail] PRIMARY KEY CLUSTERED ([payment_option_id] ASC, [language_id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[product_accessories] ADD CONSTRAINT [PK_product_accessories] PRIMARY KEY CLUSTERED ([product_id] ASC, [accessory_id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[product_bundles] ADD CONSTRAINT [PK_product_bundles] PRIMARY KEY CLUSTERED ([bundle_product_id] ASC, [product_id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[product_option_types] ADD CONSTRAINT [PK_product_option_types] PRIMARY KEY CLUSTERED ([id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[product_options] ADD CONSTRAINT [PK_product_options] PRIMARY KEY CLUSTERED ([product_option_type_id] ASC, [option_id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[product_reviews] ADD CONSTRAINT [PK_product_reviews] PRIMARY KEY CLUSTERED ([id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[products] ADD CONSTRAINT [PK_products] PRIMARY KEY CLUSTERED ([id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[products_detail] ADD CONSTRAINT [PK_products_detail] PRIMARY KEY CLUSTERED ([product_id] ASC, [language_id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[static_pages] ADD CONSTRAINT [PK_static_pages] PRIMARY KEY CLUSTERED ([id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[static_pages_detail] ADD CONSTRAINT [PK_static_pages_detail] PRIMARY KEY CLUSTERED ([static_page_id] ASC, [language_id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[static_texts] ADD CONSTRAINT [PK_static_texts] PRIMARY KEY CLUSTERED ([id] ASC, [language_id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[units] ADD CONSTRAINT [PK_units] PRIMARY KEY CLUSTERED ([id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[units_detail] ADD CONSTRAINT [PK_units_detail] PRIMARY KEY CLUSTERED ([unit_id] ASC, [language_id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[value_added_taxes] ADD CONSTRAINT [PK_value_added_taxes] PRIMARY KEY CLUSTERED ([id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[web_domains] ADD CONSTRAINT [PK_web_domains] PRIMARY KEY CLUSTERED ([id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[webshop_sessions] ADD CONSTRAINT [PK_webshop_sessions] PRIMARY KEY CLUSTERED ([id] ASC, [application_name] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);
ALTER TABLE [dbo].[webshop_settings] ADD CONSTRAINT [PK_webshop_settings] PRIMARY KEY CLUSTERED ([id] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF);

/* CREATE FOREIGN KEYS */
ALTER TABLE [dbo].[additional_services] WITH CHECK ADD CONSTRAINT [FK_additional_services_units] FOREIGN KEY([unit_id]) REFERENCES [dbo].[units] ([id]);
ALTER TABLE [dbo].[additional_services] CHECK CONSTRAINT [FK_additional_services_units];
ALTER TABLE [dbo].[additional_services_detail] WITH CHECK ADD CONSTRAINT [FK_additional_services_detail_additional_services] FOREIGN KEY([additional_service_id]) REFERENCES [dbo].[additional_services] ([id]);
ALTER TABLE [dbo].[additional_services_detail] CHECK CONSTRAINT [FK_additional_services_detail_additional_services];
ALTER TABLE [dbo].[additional_services_detail] WITH CHECK ADD CONSTRAINT [FK_additional_services_detail_languages] FOREIGN KEY([language_id]) REFERENCES [dbo].[languages] ([id]);
ALTER TABLE [dbo].[additional_services_detail] CHECK CONSTRAINT [FK_additional_services_detail_languages];
ALTER TABLE [dbo].[additional_services_detail] WITH CHECK ADD CONSTRAINT [FK_additional_services_detail_value_added_taxes] FOREIGN KEY([value_added_tax_id]) REFERENCES [dbo].[value_added_taxes] ([id]);
ALTER TABLE [dbo].[additional_services_detail] CHECK CONSTRAINT [FK_additional_services_detail_value_added_taxes];
ALTER TABLE [dbo].[campaigns] WITH CHECK ADD CONSTRAINT [FK_campaigns_languages] FOREIGN KEY([language_id]) REFERENCES [dbo].[languages] ([id]);
ALTER TABLE [dbo].[campaigns] CHECK CONSTRAINT [FK_campaigns_languages];
ALTER TABLE [dbo].[categories_detail] WITH CHECK ADD CONSTRAINT [FK_categories_detail_categories] FOREIGN KEY([category_id]) REFERENCES [dbo].[categories] ([id]);
ALTER TABLE [dbo].[categories_detail] CHECK CONSTRAINT [FK_categories_detail_categories];
ALTER TABLE [dbo].[categories_detail] WITH CHECK ADD CONSTRAINT [FK_categories_detail_languages] FOREIGN KEY([language_id]) REFERENCES [dbo].[languages] ([id]);
ALTER TABLE [dbo].[categories_detail] CHECK CONSTRAINT [FK_categories_detail_languages];
ALTER TABLE [dbo].[countries_detail] WITH CHECK ADD CONSTRAINT [FK_countries_detail_countries] FOREIGN KEY([country_id]) REFERENCES [dbo].[countries] ([id]);
ALTER TABLE [dbo].[countries_detail] CHECK CONSTRAINT [FK_countries_detail_countries];
ALTER TABLE [dbo].[countries_detail] WITH CHECK ADD CONSTRAINT [FK_countries_detail_languages] FOREIGN KEY([language_id]) REFERENCES [dbo].[languages] ([id]);
ALTER TABLE [dbo].[countries_detail] CHECK CONSTRAINT [FK_countries_detail_languages];
ALTER TABLE [dbo].[custom_themes_templates] WITH CHECK ADD CONSTRAINT [FK_custom_themes_templates_custom_themes] FOREIGN KEY([custom_theme_id]) REFERENCES [dbo].[custom_themes] ([id]);
ALTER TABLE [dbo].[custom_themes_templates] CHECK CONSTRAINT [FK_custom_themes_templates_custom_themes];
ALTER TABLE [dbo].[customers] WITH CHECK ADD CONSTRAINT [FK_customers_languages] FOREIGN KEY([language_id]) REFERENCES [dbo].[languages] ([id]);
ALTER TABLE [dbo].[customers] CHECK CONSTRAINT [FK_customers_languages];
ALTER TABLE [dbo].[customers] WITH CHECK ADD CONSTRAINT [FK_customers_countries] FOREIGN KEY([delivery_country]) REFERENCES [dbo].[countries] ([id]);
ALTER TABLE [dbo].[customers] CHECK CONSTRAINT [FK_customers_countries];
ALTER TABLE [dbo].[customers] WITH CHECK ADD CONSTRAINT [FK_customers_invoice_countries] FOREIGN KEY([invoice_country]) REFERENCES [dbo].[countries] ([id]);
ALTER TABLE [dbo].[customers] CHECK CONSTRAINT [FK_customers_invoice_countries];
ALTER TABLE [dbo].[customers_files] WITH CHECK ADD CONSTRAINT [FK_customers_files_customers] FOREIGN KEY([customer_id]) REFERENCES [dbo].[customers] ([id]);
ALTER TABLE [dbo].[customers_files] CHECK CONSTRAINT [FK_customers_files_customers];
ALTER TABLE [dbo].[customers_files] WITH CHECK ADD CONSTRAINT [FK_customers_files_products] FOREIGN KEY([product_id]) REFERENCES [dbo].[products] ([id]);
ALTER TABLE [dbo].[customers_files] CHECK CONSTRAINT [FK_customers_files_products];
ALTER TABLE [dbo].[customers_files] WITH CHECK ADD CONSTRAINT [FK_customers_files_languages] FOREIGN KEY([language_id]) REFERENCES [dbo].[languages] ([id]);
ALTER TABLE [dbo].[customers_files] CHECK CONSTRAINT [FK_customers_files_languages];
ALTER TABLE [dbo].[discount_codes] WITH CHECK ADD CONSTRAINT [FK_discount_codes_languages] FOREIGN KEY([language_id]) REFERENCES [dbo].[languages] ([id]);
ALTER TABLE [dbo].[discount_codes] CHECK CONSTRAINT [FK_discount_codes_languages];
ALTER TABLE [dbo].[discount_codes] WITH CHECK ADD CONSTRAINT [FK_discount_codes_currencies] FOREIGN KEY([currency_code]) REFERENCES [dbo].[currencies] ([currency_code]);
ALTER TABLE [dbo].[discount_codes] CHECK CONSTRAINT [FK_discount_codes_currencies];
ALTER TABLE [dbo].[gift_cards] WITH CHECK ADD CONSTRAINT [FK_gift_cards_languages] FOREIGN KEY([language_id]) REFERENCES [dbo].[languages] ([id]);
ALTER TABLE [dbo].[gift_cards] CHECK CONSTRAINT [FK_gift_cards_languages];
ALTER TABLE [dbo].[gift_cards] WITH CHECK ADD CONSTRAINT [FK_gift_cards_currencies] FOREIGN KEY([currency_code]) REFERENCES [dbo].[currencies] ([currency_code]);
ALTER TABLE [dbo].[gift_cards] CHECK CONSTRAINT [FK_gift_cards_currencies];
ALTER TABLE [dbo].[languages_detail] WITH CHECK ADD CONSTRAINT [FK_languages_detail_languages] FOREIGN KEY([language_id]) REFERENCES [dbo].[languages] ([id]);
ALTER TABLE [dbo].[languages_detail] CHECK CONSTRAINT [FK_languages_detail_languages];
ALTER TABLE [dbo].[languages_detail] WITH CHECK ADD CONSTRAINT [FK_languages_detail_translation_languages] FOREIGN KEY([translation_language_id]) REFERENCES [dbo].[languages] ([id]);
ALTER TABLE [dbo].[languages_detail] CHECK CONSTRAINT [FK_languages_detail_translation_languages];
ALTER TABLE [dbo].[option_types_detail] WITH CHECK ADD CONSTRAINT [FK_option_types_detail_languages] FOREIGN KEY([language_id]) REFERENCES [dbo].[languages] ([id]);
ALTER TABLE [dbo].[option_types_detail] CHECK CONSTRAINT [FK_option_types_detail_languages];
ALTER TABLE [dbo].[option_types_detail] WITH CHECK ADD CONSTRAINT [FK_option_types_detail_option_types] FOREIGN KEY([option_type_id]) REFERENCES [dbo].[option_types] ([id]);
ALTER TABLE [dbo].[option_types_detail] CHECK CONSTRAINT [FK_option_types_detail_option_types];
ALTER TABLE [dbo].[options] WITH CHECK ADD CONSTRAINT [FK_options_option_types] FOREIGN KEY([option_type_id]) REFERENCES [dbo].[option_types] ([id]);
ALTER TABLE [dbo].[options] CHECK CONSTRAINT [FK_options_option_types];
ALTER TABLE [dbo].[options_detail] WITH CHECK ADD CONSTRAINT [FK_options_detail_languages] FOREIGN KEY([language_id]) REFERENCES [dbo].[languages] ([id]);
ALTER TABLE [dbo].[options_detail] CHECK CONSTRAINT [FK_options_detail_languages];
ALTER TABLE [dbo].[options_detail] WITH CHECK ADD CONSTRAINT [FK_options_detail_options] FOREIGN KEY([option_id]) REFERENCES [dbo].[options] ([id]);
ALTER TABLE [dbo].[options_detail] CHECK CONSTRAINT [FK_options_detail_options];
ALTER TABLE [dbo].[order_rows] WITH CHECK ADD CONSTRAINT [FK_order_rows_orders] FOREIGN KEY([order_id]) REFERENCES [dbo].[orders] ([id]);
ALTER TABLE [dbo].[order_rows] CHECK CONSTRAINT [FK_order_rows_orders];
ALTER TABLE [dbo].[order_rows] WITH CHECK ADD CONSTRAINT [FK_order_rows_units] FOREIGN KEY([unit_id]) REFERENCES [dbo].[units] ([id]);
ALTER TABLE [dbo].[order_rows] CHECK CONSTRAINT [FK_order_rows_units];
ALTER TABLE [dbo].[orders] WITH CHECK ADD CONSTRAINT [FK_orders_customers] FOREIGN KEY([customer_id]) REFERENCES [dbo].[customers] ([id]);
ALTER TABLE [dbo].[orders] CHECK CONSTRAINT [FK_orders_customers];
ALTER TABLE [dbo].[orders] WITH CHECK ADD CONSTRAINT [FK_orders_delivery_countries] FOREIGN KEY([delivery_country_id]) REFERENCES [dbo].[countries] ([id]);
ALTER TABLE [dbo].[orders] CHECK CONSTRAINT [FK_orders_delivery_countries];
ALTER TABLE [dbo].[orders] WITH CHECK ADD CONSTRAINT [FK_orders_invoice_countries] FOREIGN KEY([invoice_country_id]) REFERENCES [dbo].[countries] ([id]);
ALTER TABLE [dbo].[orders] CHECK CONSTRAINT [FK_orders_invoice_countries];
ALTER TABLE [dbo].[orders] WITH CHECK ADD CONSTRAINT [FK_orders_payment_options] FOREIGN KEY([payment_option]) REFERENCES [dbo].[payment_options] ([id]);
ALTER TABLE [dbo].[orders] CHECK CONSTRAINT [FK_orders_payment_options];
ALTER TABLE [dbo].[orders] WITH CHECK ADD CONSTRAINT [FK_orders_companies] FOREIGN KEY([company_id]) REFERENCES [dbo].[companies] ([id]);
ALTER TABLE [dbo].[orders] CHECK CONSTRAINT [FK_orders_companies];
ALTER TABLE [dbo].[orders_gift_cards] WITH CHECK ADD CONSTRAINT [FK_orders_gift_cards_orders] FOREIGN KEY([order_id]) REFERENCES [dbo].[orders] ([id]);
ALTER TABLE [dbo].[orders_gift_cards] CHECK CONSTRAINT [FK_orders_gift_cards_orders];
ALTER TABLE [dbo].[newsletters] WITH CHECK ADD CONSTRAINT [FK_newsletters_languages] FOREIGN KEY([language_id]) REFERENCES [dbo].[languages] ([id]);
ALTER TABLE [dbo].[newsletters] CHECK CONSTRAINT [FK_newsletters_languages];
ALTER TABLE [dbo].[payment_options] WITH CHECK ADD CONSTRAINT [FK_payment_options_units] FOREIGN KEY([unit_id]) REFERENCES [dbo].[units] ([id]);
ALTER TABLE [dbo].[payment_options] CHECK CONSTRAINT [FK_payment_options_units];
ALTER TABLE [dbo].[payment_options_detail] WITH CHECK ADD CONSTRAINT [FK_payment_options_detail_languages] FOREIGN KEY([language_id]) REFERENCES [dbo].[languages] ([id]);
ALTER TABLE [dbo].[payment_options_detail] CHECK CONSTRAINT [FK_payment_options_detail_languages];
ALTER TABLE [dbo].[payment_options_detail] WITH CHECK ADD CONSTRAINT [FK_payment_options_detail_payment_options] FOREIGN KEY([payment_option_id]) REFERENCES [dbo].[payment_options] ([id]);
ALTER TABLE [dbo].[payment_options_detail] CHECK CONSTRAINT [FK_payment_options_detail_payment_options];
ALTER TABLE [dbo].[payment_options_detail] WITH CHECK ADD CONSTRAINT [FK_payment_options_detail_value_added_taxes] FOREIGN KEY([value_added_tax_id]) REFERENCES [dbo].[value_added_taxes] ([id]);
ALTER TABLE [dbo].[payment_options_detail] CHECK CONSTRAINT [FK_payment_options_detail_value_added_taxes];
ALTER TABLE [dbo].[product_accessories] WITH CHECK ADD CONSTRAINT [FK_product_accessories_accessory_product] FOREIGN KEY([accessory_id]) REFERENCES [dbo].[products] ([id]);
ALTER TABLE [dbo].[product_accessories] CHECK CONSTRAINT [FK_product_accessories_accessory_product];
ALTER TABLE [dbo].[product_accessories] WITH CHECK ADD CONSTRAINT [FK_product_accessories_products] FOREIGN KEY([product_id]) REFERENCES [dbo].[products] ([id]);
ALTER TABLE [dbo].[product_accessories] CHECK CONSTRAINT [FK_product_accessories_products];
ALTER TABLE [dbo].[product_bundles] WITH CHECK ADD CONSTRAINT [FK_product_bundles_product] FOREIGN KEY([product_id]) REFERENCES [dbo].[products] ([id]);
ALTER TABLE [dbo].[product_bundles] CHECK CONSTRAINT [FK_product_bundles_product];
ALTER TABLE [dbo].[product_bundles] WITH CHECK ADD CONSTRAINT [FK_product_bundles_bundle_product] FOREIGN KEY([bundle_product_id]) REFERENCES [dbo].[products] ([id]);
ALTER TABLE [dbo].[product_bundles] CHECK CONSTRAINT [FK_product_bundles_bundle_product];
ALTER TABLE [dbo].[product_option_types] WITH CHECK ADD CONSTRAINT [FK_product_option_types_option_types] FOREIGN KEY([option_type_id]) REFERENCES [dbo].[option_types] ([id]);
ALTER TABLE [dbo].[product_option_types] CHECK CONSTRAINT [FK_product_option_types_option_types];
ALTER TABLE [dbo].[product_option_types] WITH CHECK ADD CONSTRAINT [FK_product_option_types_products] FOREIGN KEY([product_id]) REFERENCES [dbo].[products] ([id]);
ALTER TABLE [dbo].[product_option_types] CHECK CONSTRAINT [FK_product_option_types_products];
ALTER TABLE [dbo].[product_options] WITH CHECK ADD CONSTRAINT [FK_product_options_options] FOREIGN KEY([option_id]) REFERENCES [dbo].[options] ([id]);
ALTER TABLE [dbo].[product_options] CHECK CONSTRAINT [FK_product_options_options];
ALTER TABLE [dbo].[product_options] WITH CHECK ADD CONSTRAINT [FK_product_options_product_option_types] FOREIGN KEY([product_option_type_id]) REFERENCES [dbo].[product_option_types] ([id]);
ALTER TABLE [dbo].[product_options] CHECK CONSTRAINT [FK_product_options_product_option_types];
ALTER TABLE [dbo].[product_reviews] WITH CHECK ADD CONSTRAINT [FK_product_reviews_customers] FOREIGN KEY([customer_id]) REFERENCES [dbo].[customers] ([id]);
ALTER TABLE [dbo].[product_reviews] CHECK CONSTRAINT [FK_product_reviews_customers];
ALTER TABLE [dbo].[product_reviews] WITH CHECK ADD CONSTRAINT [FK_product_reviews_languages] FOREIGN KEY([language_id]) REFERENCES [dbo].[languages] ([id]);
ALTER TABLE [dbo].[product_reviews] CHECK CONSTRAINT [FK_product_reviews_languages];
ALTER TABLE [dbo].[product_reviews] WITH CHECK ADD CONSTRAINT [FK_product_reviews_products] FOREIGN KEY([product_id]) REFERENCES [dbo].[products] ([id]);
ALTER TABLE [dbo].[product_reviews] CHECK CONSTRAINT [FK_product_reviews_products];
ALTER TABLE [dbo].[products] WITH CHECK ADD CONSTRAINT [FK_products_categories] FOREIGN KEY([category_id]) REFERENCES [dbo].[categories] ([id]);
ALTER TABLE [dbo].[products] CHECK CONSTRAINT [FK_products_categories];
ALTER TABLE [dbo].[products] WITH CHECK ADD CONSTRAINT [FK_products_units] FOREIGN KEY([unit_id]) REFERENCES [dbo].[units] ([id]);
ALTER TABLE [dbo].[products] CHECK CONSTRAINT [FK_products_units];
ALTER TABLE [dbo].[products_detail] WITH CHECK ADD CONSTRAINT [FK_products_detail_languages] FOREIGN KEY([language_id]) REFERENCES [dbo].[languages] ([id]);
ALTER TABLE [dbo].[products_detail] CHECK CONSTRAINT [FK_products_detail_languages];
ALTER TABLE [dbo].[products_detail] WITH CHECK ADD CONSTRAINT [FK_products_detail_products] FOREIGN KEY([product_id]) REFERENCES [dbo].[products] ([id]);
ALTER TABLE [dbo].[products_detail] CHECK CONSTRAINT [FK_products_detail_products];
ALTER TABLE [dbo].[products_detail] WITH CHECK ADD CONSTRAINT [FK_products_detail_value_added_taxes] FOREIGN KEY([value_added_tax_id]) REFERENCES [dbo].[value_added_taxes] ([id]);
ALTER TABLE [dbo].[products_detail] CHECK CONSTRAINT [FK_products_detail_value_added_taxes];
ALTER TABLE [dbo].[static_pages_detail] WITH CHECK ADD CONSTRAINT [FK_static_pages_detail_languages] FOREIGN KEY([language_id]) REFERENCES [dbo].[languages] ([id]);
ALTER TABLE [dbo].[static_pages_detail] CHECK CONSTRAINT [FK_static_pages_detail_languages];
ALTER TABLE [dbo].[static_pages_detail] WITH CHECK ADD CONSTRAINT [FK_static_pages_detail_pages] FOREIGN KEY([static_page_id]) REFERENCES [dbo].[static_pages] ([id]);
ALTER TABLE [dbo].[static_pages_detail] CHECK CONSTRAINT [FK_static_pages_detail_pages];
ALTER TABLE [dbo].[static_texts] WITH CHECK ADD CONSTRAINT [FK_static_texts_languages] FOREIGN KEY([language_id]) REFERENCES [dbo].[languages] ([id]);
ALTER TABLE [dbo].[static_texts] CHECK CONSTRAINT [FK_static_texts_languages];
ALTER TABLE [dbo].[units_detail] WITH CHECK ADD CONSTRAINT [FK_units_detail_languages] FOREIGN KEY([language_id]) REFERENCES [dbo].[languages] ([id]);
ALTER TABLE [dbo].[units_detail] CHECK CONSTRAINT [FK_units_detail_languages];
ALTER TABLE [dbo].[units_detail] WITH CHECK ADD CONSTRAINT [FK_units_detail_units] FOREIGN KEY([unit_id]) REFERENCES [dbo].[units] ([id]);
ALTER TABLE [dbo].[units_detail] CHECK CONSTRAINT [FK_units_detail_units];
ALTER TABLE [dbo].[web_domains] WITH CHECK ADD CONSTRAINT [FK_web_domains_back_end_languages] FOREIGN KEY([back_end_language]) REFERENCES [dbo].[languages] ([id]);
ALTER TABLE [dbo].[web_domains] CHECK CONSTRAINT [FK_web_domains_back_end_languages];
ALTER TABLE [dbo].[web_domains] WITH CHECK ADD CONSTRAINT [FK_web_domains_currencies] FOREIGN KEY([currency]) REFERENCES [dbo].[currencies] ([currency_code]);
ALTER TABLE [dbo].[web_domains] CHECK CONSTRAINT [FK_web_domains_currencies];
ALTER TABLE [dbo].[web_domains] WITH CHECK ADD CONSTRAINT [FK_web_domains_front_end_languages] FOREIGN KEY([front_end_language]) REFERENCES [dbo].[languages] ([id]);
ALTER TABLE [dbo].[web_domains] CHECK CONSTRAINT [FK_web_domains_front_end_languages];
ALTER TABLE [dbo].[web_domains] WITH CHECK ADD CONSTRAINT [FK_web_domains_countries] FOREIGN KEY([country_id]) REFERENCES [dbo].[countries] ([id]);
ALTER TABLE [dbo].[web_domains] CHECK CONSTRAINT [FK_web_domains_countries];
ALTER TABLE [dbo].[web_domains] WITH CHECK ADD CONSTRAINT [FK_web_domains_companies] FOREIGN KEY([company_id]) REFERENCES [dbo].[companies] ([id]);
ALTER TABLE [dbo].[web_domains] CHECK CONSTRAINT [FK_web_domains_companies];

/* CREATE INDEXES */
CREATE NONCLUSTERED INDEX [IX_additional_services_detail_language] ON [dbo].[additional_services_detail] ([language_id] ASC, [inactive] ASC);
CREATE NONCLUSTERED INDEX [IX_campaigns_language] ON [dbo].[campaigns] ([language_id] ASC, [category_name] ASC, [inactive] ASC);
CREATE NONCLUSTERED INDEX [IX_categories_parent_id] ON [dbo].[categories] ([parent_category_id] ASC);
CREATE NONCLUSTERED INDEX [IX_categories_detail_language] ON [dbo].[categories_detail] ([language_id] ASC, [inactive] ASC);
CREATE NONCLUSTERED INDEX [IX_countries_detail_language] ON [dbo].[countries_detail] ([language_id] ASC);
CREATE NONCLUSTERED INDEX [IX_customers_facebook_id] ON [dbo].[customers] ([facebook_user_id] ASC);
CREATE NONCLUSTERED INDEX [IX_customers_google_id] ON [dbo].[customers] ([google_user_id] ASC);
CREATE NONCLUSTERED INDEX [IX_customers_org_number] ON [dbo].[customers] ([org_number] ASC);
CREATE NONCLUSTERED INDEX [IX_customers_language] ON [dbo].[customers] ([language_id] ASC, [newsletter] ASC);
CREATE NONCLUSTERED INDEX [IX_inspiration_image_maps_language] ON [dbo].[inspiration_image_maps] ([language_id] ASC, [category_id] ASC);
CREATE NONCLUSTERED INDEX [IX_languages_detail_language] ON [dbo].[languages_detail] ([translation_language_id] ASC);
CREATE NONCLUSTERED INDEX [IX_options_option_type_id] ON [dbo].[options] ([option_type_id] ASC);
CREATE NONCLUSTERED INDEX [IX_options_detail_language] ON [dbo].[options_detail] ([language_id] ASC);
CREATE NONCLUSTERED INDEX [IX_option_types_detail_language] ON [dbo].[option_types_detail] ([language_id] ASC);
CREATE NONCLUSTERED INDEX [IX_orders_customer_id] ON [dbo].[orders] ([customer_id] ASC);
CREATE NONCLUSTERED INDEX [IX_orders_discount_code] ON [dbo].[orders] ([discount_code] ASC);
CREATE NONCLUSTERED INDEX [IX_orders_exported_to_erp] ON [dbo].[orders] ([exported_to_erp] ASC, [order_status] ASC, [company_id] ASC);
CREATE NONCLUSTERED INDEX [IX_orders_document_type] ON [dbo].[orders] ([document_type] ASC, [country_code] ASC);
CREATE NONCLUSTERED INDEX [IX_orders_gift_cards_gift_card_id] ON [dbo].[orders_gift_cards] ([gift_card_id] ASC);
CREATE NONCLUSTERED INDEX [IX_payment_options_detail_language] ON [dbo].[payment_options_detail] ([language_id] ASC, [inactive] ASC);
CREATE NONCLUSTERED INDEX [IX_products_category_id] ON [dbo].[products] ([category_id] ASC);
CREATE NONCLUSTERED INDEX [IX_products_detail_language] ON [dbo].[products_detail] ([language_id] ASC, [inactive] ASC);
CREATE NONCLUSTERED INDEX [IX_product_option_types_product_id] ON [dbo].[product_option_types] ([product_id] ASC);
CREATE NONCLUSTERED INDEX [IX_product_reviews_customer_id] ON [dbo].[product_reviews] ([customer_id] ASC, [product_id] ASC, [id] ASC);
CREATE NONCLUSTERED INDEX [IX_product_reviews_product_id] ON [dbo].[product_reviews] ([product_id] ASC, [language_id] ASC);
CREATE NONCLUSTERED INDEX [IX_static_pages_connection] ON [dbo].[static_pages] ([connected_to_page] ASC);
CREATE NONCLUSTERED INDEX [IX_static_pages_detail_language] ON [dbo].[static_pages_detail] ([language_id] ASC, [inactive] ASC);
CREATE NONCLUSTERED INDEX [IX_static_texts_language] ON [dbo].[static_texts] ([language_id] ASC);
CREATE NONCLUSTERED INDEX [IX_units_detail_language] ON [dbo].[units_detail] ([language_id] ASC);
CREATE NONCLUSTERED INDEX [IX_webshop_sessions_date] ON [dbo].[webshop_sessions] ([expires_date] ASC);

/* REBUILD INDEXES */
ALTER INDEX ALL ON [dbo].[additional_services] REBUILD;
ALTER INDEX ALL ON [dbo].[additional_services_detail] REBUILD;
ALTER INDEX ALL ON [dbo].[administrators] REBUILD;
ALTER INDEX ALL ON [dbo].[campaigns] REBUILD;
ALTER INDEX ALL ON [dbo].[categories] REBUILD;
ALTER INDEX ALL ON [dbo].[categories_detail] REBUILD;
ALTER INDEX ALL ON [dbo].[companies] REBUILD;
ALTER INDEX ALL ON [dbo].[countries] REBUILD;
ALTER INDEX ALL ON [dbo].[countries_detail] REBUILD;
ALTER INDEX ALL ON [dbo].[currencies] REBUILD;
ALTER INDEX ALL ON [dbo].[custom_themes] REBUILD;
ALTER INDEX ALL ON [dbo].[custom_themes_templates] REBUILD;
ALTER INDEX ALL ON [dbo].[customers_files] REBUILD;
ALTER INDEX ALL ON [dbo].[customers] REBUILD;
ALTER INDEX ALL ON [dbo].[discount_codes] REBUILD;
ALTER INDEX ALL ON [dbo].[gift_cards] REBUILD;
ALTER INDEX ALL ON [dbo].[inspiration_image_maps] REBUILD;
ALTER INDEX ALL ON [dbo].[languages] REBUILD;
ALTER INDEX ALL ON [dbo].[languages_detail] REBUILD;
ALTER INDEX ALL ON [dbo].[option_types] REBUILD;
ALTER INDEX ALL ON [dbo].[option_types_detail] REBUILD;
ALTER INDEX ALL ON [dbo].[options] REBUILD;
ALTER INDEX ALL ON [dbo].[options_detail] REBUILD;
ALTER INDEX ALL ON [dbo].[order_rows] REBUILD;
ALTER INDEX ALL ON [dbo].[orders] REBUILD;
ALTER INDEX ALL ON [dbo].[orders_gift_cards] REBUILD;
ALTER INDEX ALL ON [dbo].[newsletters] REBUILD;
ALTER INDEX ALL ON [dbo].[payment_options] REBUILD;
ALTER INDEX ALL ON [dbo].[payment_options_detail] REBUILD;
ALTER INDEX ALL ON [dbo].[product_accessories] REBUILD;
ALTER INDEX ALL ON [dbo].[product_bundles] REBUILD;
ALTER INDEX ALL ON [dbo].[product_option_types] REBUILD;
ALTER INDEX ALL ON [dbo].[product_options] REBUILD;
ALTER INDEX ALL ON [dbo].[product_reviews] REBUILD;
ALTER INDEX ALL ON [dbo].[products] REBUILD;
ALTER INDEX ALL ON [dbo].[products_detail] REBUILD;
ALTER INDEX ALL ON [dbo].[static_pages] REBUILD;
ALTER INDEX ALL ON [dbo].[static_pages_detail] REBUILD;
ALTER INDEX ALL ON [dbo].[static_texts] REBUILD;
ALTER INDEX ALL ON [dbo].[units] REBUILD;
ALTER INDEX ALL ON [dbo].[units_detail] REBUILD;
ALTER INDEX ALL ON [dbo].[value_added_taxes] REBUILD;
ALTER INDEX ALL ON [dbo].[web_domains] REBUILD;
ALTER INDEX ALL ON [dbo].[webshop_sessions] REBUILD;
ALTER INDEX ALL ON [dbo].[webshop_settings] REBUILD;

/* EXCECUTE THE TRANSACTION */
COMMIT;